import json
import re
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from korvo_server.config import REPO_ROOT


def c_macro_string(value: object) -> str:
    return (
        str(value if value is not None else "")
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r\n", " ")
        .replace("\n", " ")
    )


def build_config_dict(conn: sqlite3.Connection) -> dict:
    cur = conn.cursor()
    active_wifi = cur.execute(
        "SELECT ssid, password FROM wifi_networks WHERE is_active = 1"
    ).fetchone()
    rows = cur.execute("SELECT key, value FROM settings").fetchall()
    settings = {r["key"]: r["value"] for r in rows}
    return {
        "wifi": {"ssid": active_wifi["ssid"], "password": active_wifi["password"]} if active_wifi else None,
        "settings": settings,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


def _unescape_c_string(s: str) -> str:
    return s.replace("\\\\", "\x00").replace('\\"', '"').replace("\x00", "\\")


def _preserve_wifi_from_header(header_path: Path) -> dict | None:
    """Read last SSID/password from korvo_config.h (used when DB has no active row but we must not wipe macros)."""
    if not header_path.is_file():
        return None
    text = header_path.read_text(encoding="utf-8")
    m1 = re.search(r'#define\s+KORVO_WIFI_SSID\s+"((?:\\.|[^"])*)"', text)
    m2 = re.search(r'#define\s+KORVO_WIFI_PASSWORD\s+"((?:\\.|[^"])*)"', text)
    if not m1 or not m2:
        return None
    ssid = _unescape_c_string(m1.group(1))
    password = _unescape_c_string(m2.group(1))
    if not ssid and not password:
        return None
    return {"ssid": ssid, "password": password}


def write_config_files(config: dict, *, preserve_wifi_if_missing: bool = False) -> None:
    skainet_main = REPO_ROOT / "esp-skainet" / "examples" / "wake_word_detection" / "wakenet" / "main"
    app_main = REPO_ROOT / "korvo-app" / "main"
    app_header = app_main / "korvo_config.h"

    cfg = dict(config)
    if preserve_wifi_if_missing and cfg.get("wifi") is None:
        preserved = _preserve_wifi_from_header(app_header)
        if preserved:
            cfg["wifi"] = preserved

    json_text = json.dumps(cfg, indent=2)

    lines = [
        "// Auto-generated by korvo-server — DO NOT EDIT",
        "#ifndef KORVO_CONFIG_H",
        "#define KORVO_CONFIG_H",
        "",
    ]
    if cfg.get("wifi"):
        lines.append(f'#define KORVO_WIFI_SSID "{c_macro_string(cfg["wifi"]["ssid"])}"')
        lines.append(f'#define KORVO_WIFI_PASSWORD "{c_macro_string(cfg["wifi"]["password"])}"')
    else:
        lines.extend(['#define KORVO_WIFI_SSID ""', '#define KORVO_WIFI_PASSWORD ""', ""])
    for key, value in cfg["settings"].items():
        macro = "KORVO_CFG_" + re.sub(r"[^A-Z0-9]+", "_", key.upper()).strip("_")
        lines.append(f'#define {macro} "{c_macro_string(value)}"')
    lines.extend(["", "#endif // KORVO_CONFIG_H", ""])
    header_text = "\n".join(lines)

    skainet_main.mkdir(parents=True, exist_ok=True)
    app_main.mkdir(parents=True, exist_ok=True)
    (skainet_main / "korvo_config.json").write_text(json_text, encoding="utf-8")
    (skainet_main / "korvo_config.h").write_text(header_text, encoding="utf-8")
    (app_main / "korvo_config.json").write_text(json_text, encoding="utf-8")
    (app_main / "korvo_config.h").write_text(header_text, encoding="utf-8")


def read_config(conn: sqlite3.Connection) -> dict:
    """DB → dict only (does not touch korvo_config.* on disk)."""
    return build_config_dict(conn)


def generate_config(conn: sqlite3.Connection, *, preserve_wifi_if_missing: bool = False) -> dict:
    """DB → dict and write korvo_config.h / korvo_config.json under korvo-app and esp-skainet paths."""
    config = build_config_dict(conn)
    write_config_files(config, preserve_wifi_if_missing=preserve_wifi_if_missing)
    return config


def has_active_wifi(conn: sqlite3.Connection) -> bool:
    row = conn.execute("SELECT 1 FROM wifi_networks WHERE is_active = 1 LIMIT 1").fetchone()
    return row is not None


def _find_external_db_candidate() -> Path | None:
    current = (REPO_ROOT / "korvo-server" / "korvo.db").resolve()
    candidates: list[Path] = []
    for db_file in REPO_ROOT.glob("*/korvo.db"):
        try:
            resolved = db_file.resolve()
        except OSError:
            continue
        if resolved == current:
            continue
        if db_file.is_file():
            candidates.append(db_file)
    if not candidates:
        return None
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0]


def _merge_external_sqlite_wifi(conn: sqlite3.Connection) -> bool:
    """If this DB has no wifi rows, copy them from another Korvo DB in this repo."""
    external = _find_external_db_candidate()
    if external is None:
        return False
    attached = False
    try:
        conn.execute("ATTACH DATABASE ? AS legdb", (str(external),))
        attached = True
        if not conn.execute(
            "SELECT 1 FROM legdb.sqlite_master WHERE type='table' AND name='wifi_networks'"
        ).fetchone():
            return False
        n = conn.execute("SELECT COUNT(*) FROM legdb.wifi_networks").fetchone()[0]
        if not n:
            return False
        conn.execute(
            "INSERT INTO main.wifi_networks (ssid, password, is_active) "
            "SELECT ssid, password, COALESCE(is_active, 0) FROM legdb.wifi_networks"
        )
        conn.commit()
        return True
    except sqlite3.OperationalError as e:
        conn.rollback()
        print(f"[korvo] external WiFi merge failed: {e}")
        return False
    finally:
        if attached:
            try:
                conn.execute("DETACH DATABASE legdb")
            except sqlite3.OperationalError:
                pass


def _seed_wifi_from_header(conn: sqlite3.Connection) -> bool:
    """If DB still has no networks, insert one row from korvo-app/main/korvo_config.h (non-empty SSID)."""
    header = REPO_ROOT / "korvo-app" / "main" / "korvo_config.h"
    data = _preserve_wifi_from_header(header)
    if not data or not (data.get("ssid") or "").strip():
        return False
    conn.execute(
        "INSERT INTO wifi_networks (ssid, password, is_active) VALUES (?, ?, 1)",
        (data["ssid"].strip(), (data.get("password") or "")),
    )
    conn.commit()
    return True


def hydrate_wifi_db_from_external_sources(conn: sqlite3.Connection) -> bool:
    """When wifi_networks is empty, pull from external korvo.db and/or existing korvo_config.h."""
    if conn.execute("SELECT 1 FROM wifi_networks LIMIT 1").fetchone():
        return False
    if _merge_external_sqlite_wifi(conn):
        return True
    return _seed_wifi_from_header(conn)
