// Auto-generated by korvo-config-server — DO NOT EDIT
#ifndef KORVO_CONFIG_H
#define KORVO_CONFIG_H

#define KORVO_WIFI_SSID "The Von"
#define KORVO_WIFI_PASSWORD "Sausage69"


#endif // KORVO_CONFIG_H
