// Auto-generated by korvo-server — DO NOT EDIT
#ifndef KORVO_CONFIG_H
#define KORVO_CONFIG_H

#define KORVO_WIFI_SSID ""
#define KORVO_WIFI_PASSWORD ""

#define KORVO_CFG_ESP_IP "192.168.1.28"
#define KORVO_CFG_LAST_BOARD_HOST "korvo.local"
#define KORVO_CFG_LAST_BOARD_STA_IP "192.168.1.28"
#define KORVO_CFG_WAKE_WORD "hilexin"
#define KORVO_CFG_AGENT_ENDPOINT ""
#define KORVO_CFG_BOARD_API_TOKEN ""

#endif // KORVO_CONFIG_H
