// Auto-generated WiFi configuration — do not edit manually
// Generated by korvo-config-server from web UI
#ifndef KORVO_CONFIG_H
#define KORVO_CONFIG_H

#define KORVO_WIFI_SSID     "The Von"
#define KORVO_WIFI_PASSWORD  "Sausage69"

#endif // KORVO_CONFIG_H